# Generated by Django 5.1.1 on 2024-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='новости дня')),
                ('image1', models.ImageField(upload_to='logo_image/', verbose_name='фото_1')),
                ('image2', models.ImageField(upload_to='logo_image/', verbose_name='фото_2')),
                ('image3', models.ImageField(upload_to='logo_image/', verbose_name='фото_3')),
                ('text1', models.CharField(max_length=155, verbose_name='первое новости')),
                ('text2', models.CharField(max_length=155, verbose_name='второе новости')),
                ('text3', models.CharField(max_length=155, verbose_name='третое новости')),
            ],
        ),
    ]
